openapi: 3.0.4
info:
  title: ClipMetr - OpenAPI 3.0
  description: |-
    This is a Swagger Documentation for ClipMetr.
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: clips
    description: Things you can do with clips.
paths:
  /test:
    get:
      tags:
        - clips
      summary: Test the test endpoint
      description: Da test
      operationId: test
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/TestDto'
  /buckets:
    get:
      tags:
        - clips
      summary: shows a list of buckets


components:
  schemas:
    TestDto:
      type: object
      properties:
        message:
          type: string
          example: This is a message
